openapi: 3.0.0
info:
  title: Overview Data
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/myrole:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                enum: 
                  - "ADMIN"
                  # - "CLIENT"
                  # - "READONLY"
                  # - "CEO"
